// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using uFrame.IOC;
using uFrame.Kernel;
using uFrame.MVVM;


public class MainSystemLoaderBase : uFrame.Kernel.SystemLoader {
    
    private GameController _GameController;
    
    private CubeController _CubeController;
    
    [uFrame.IOC.InjectAttribute()]
    public virtual GameController GameController {
        get {
            if (_GameController==null) {
                _GameController = Container.CreateInstance(typeof(GameController)) as GameController;;
            }
            return _GameController;
        }
        set {
            _GameController = value;
        }
    }
    
    [uFrame.IOC.InjectAttribute()]
    public virtual CubeController CubeController {
        get {
            if (_CubeController==null) {
                _CubeController = Container.CreateInstance(typeof(CubeController)) as CubeController;;
            }
            return _CubeController;
        }
        set {
            _CubeController = value;
        }
    }
    
    public override void Load() {
        Container.RegisterViewModelManager<GameViewModel>(new ViewModelManager<GameViewModel>());
        Container.RegisterController<GameController>(GameController);
        Container.RegisterViewModelManager<CubeViewModel>(new ViewModelManager<CubeViewModel>());
        Container.RegisterController<CubeController>(CubeController);
    }
}
