// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using uFrame.IOC;
using uFrame.Kernel;
using uFrame.MVVM;
using uFrame.MVVM.Bindings;
using uFrame.Serialization;
using UnityEngine;
using UniRx;


public partial class GameViewModelBase : uFrame.MVVM.ViewModel {
    
    private ModelCollection<CubeViewModel> _Cubes;
    
    private Signal<AddCubeCommand> _AddCube;
    
    public GameViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
    
    public virtual ModelCollection<CubeViewModel> Cubes {
        get {
            return _Cubes;
        }
        set {
            _Cubes = value;
        }
    }
    
    public virtual Signal<AddCubeCommand> AddCube {
        get {
            return _AddCube;
        }
        set {
            _AddCube = value;
        }
    }
    
    public override void Bind() {
        base.Bind();
        this.AddCube = new Signal<AddCubeCommand>(this);
        _Cubes = new ModelCollection<CubeViewModel>(this, "Cubes");
    }
    
    public virtual void ExecuteAddCube() {
        this.AddCube.OnNext(new AddCubeCommand());
    }
    
    public override void Read(ISerializerStream stream) {
        base.Read(stream);
        if (stream.DeepSerialize) {
            this.Cubes.Clear();
            this.Cubes.AddRange(stream.DeserializeObjectArray<CubeViewModel>("Cubes"));
        }
    }
    
    public override void Write(ISerializerStream stream) {
        base.Write(stream);
        if (stream.DeepSerialize) stream.SerializeArray("Cubes", this.Cubes);
    }
    
    protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModelCommandInfo> list) {
        base.FillCommands(list);
        list.Add(new ViewModelCommandInfo("AddCube", AddCube) { ParameterType = typeof(void) });
    }
    
    protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModelPropertyInfo> list) {
        base.FillProperties(list);
        list.Add(new ViewModelPropertyInfo(_Cubes, true, true, false, false));
    }
}

public partial class GameViewModel {
    
    public GameViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
}

public partial class CubeViewModelBase : uFrame.MVVM.ViewModel {
    
    public CubeViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
    
    public override void Bind() {
        base.Bind();
    }
    
    public override void Read(ISerializerStream stream) {
        base.Read(stream);
    }
    
    public override void Write(ISerializerStream stream) {
        base.Write(stream);
    }
    
    protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModelCommandInfo> list) {
        base.FillCommands(list);
    }
    
    protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModelPropertyInfo> list) {
        base.FillProperties(list);
    }
}

public partial class CubeViewModel {
    
    public CubeViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
}
